// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class Answer
{
    public int Id { get; set; }

    public int Qid { get; set; }

    public string Answer1 { get; set; }

    public virtual Question QidNavigation { get; set; }
}