// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class AttractionTicketStock
{
    public int Id { get; set; }

    public int AttractionTicketId { get; set; }

    public int Stock { get; set; }

    public DateTime? ReserveDate { get; set; }

    public virtual AttractionTicket AttractionTicket { get; set; }
}