// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class AttrationOrderItem
{
    public int Id { get; set; }

    public int AttractionOrderId { get; set; }

    public int AttractionTicketId { get; set; }

    public int Qty { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual AttractionOrder AttractionOrder { get; set; }

    public virtual AttractionTicket AttractionTicket { get; set; }
}