// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class AttractionImage
{
    public int Id { get; set; }

    public int AttractionId { get; set; }

    public string FileName { get; set; }

    public string Description { get; set; }

    public virtual Attraction Attraction { get; set; }
}