// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class AttractionTicket
{
    public int Id { get; set; }

    public int AttractionId { get; set; }

    public decimal Price { get; set; }

    public int Discount { get; set; }

    public int AttractionTicketTypeId { get; set; }

    public bool TicketStatus { get; set; }

    public string TicketTitle { get; set; }

    public string TicketDetail { get; set; }

    public virtual Attraction Attraction { get; set; }

    public virtual ICollection<AttractionCartItem> AttractionCartItems { get; set; } = new List<AttractionCartItem>();

    public virtual ICollection<AttractionTicketStock> AttractionTicketStocks { get; set; } = new List<AttractionTicketStock>();

    public virtual AttractionTicketType AttractionTicketType { get; set; }

    public virtual ICollection<AttrationOrderItem> AttrationOrderItems { get; set; } = new List<AttrationOrderItem>();
}