// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class Attraction
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int AttractionCategoryId { get; set; }

    public int CityId { get; set; }

    public string Description { get; set; }

    public string MainImage { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public virtual AttractionCategory AttractionCategory { get; set; }

    public virtual ICollection<AttractionContentContext> AttractionContentContexts { get; set; } = new List<AttractionContentContext>();

    public virtual ICollection<AttractionContentImage> AttractionContentImages { get; set; } = new List<AttractionContentImage>();

    public virtual ICollection<AttractionImage> AttractionImages { get; set; } = new List<AttractionImage>();

    public virtual ICollection<AttractionTicket> AttractionTickets { get; set; } = new List<AttractionTicket>();

    public virtual ICollection<PackageAttractionItem> PackageAttractionItems { get; set; } = new List<PackageAttractionItem>();
}