// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class AttractionCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Attraction> Attractions { get; set; } = new List<Attraction>();
}