// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class AttractionContentImage
{
    public int Id { get; set; }

    public int AttractionId { get; set; }

    public string ImageType { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public virtual Attraction Attraction { get; set; }
}