// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class BillItem
{
    public int Id { get; set; }

    public int BillId { get; set; }

    public int ItemId { get; set; }

    public int ServiceCategory { get; set; }

    public virtual Bill Bill { get; set; }
}