// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class Bill
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime DateTime { get; set; }

    public int Total { get; set; }

    public virtual ICollection<BillItem> BillItems { get; set; } = new List<BillItem>();

    public virtual Member Member { get; set; }
}