// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class Car
{
    public int Id { get; set; }

    public int CarModelId { get; set; }

    public string CarLicenceId { get; set; }

    public int Mileage { get; set; }

    public int CityId { get; set; }

    public virtual CarModel CarModel { get; set; }

    public virtual ICollection<CarOrder> CarOrders { get; set; } = new List<CarOrder>();

    public virtual City City { get; set; }
}