// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class CarModel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int CarBrandId { get; set; }

    public int CarTransmissionId { get; set; }

    public int CarEnergyTypeId { get; set; }

    public int Seats { get; set; }

    public int FeePerDay { get; set; }

    public string MainImage { get; set; }

    public int MaintenanceMileage { get; set; }

    public virtual CarBrand CarBrand { get; set; }

    public virtual CarEnergyType CarEnergyType { get; set; }

    public virtual ICollection<CarModelImage> CarModelImages { get; set; } = new List<CarModelImage>();

    public virtual CarTransmission CarTransmission { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}