// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class CarOrder
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int CarId { get; set; }

    public int? AdminId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime EndDateTime { get; set; }

    public int Price { get; set; }

    public int CarOrderStatusId { get; set; }

    public virtual Beadmin Admin { get; set; }

    public virtual Car Car { get; set; }

    public virtual CarOrderStatus CarOrderStatus { get; set; }

    public virtual Member Member { get; set; }
}