// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class CommentImage
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public int CommentId { get; set; }

    public virtual Comment Comment { get; set; }
}