// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class Hotel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int DistrictId { get; set; }

    public string Address { get; set; }

    public decimal Grade { get; set; }

    public string Phone { get; set; }

    public int? Level { get; set; }

    public string MainImage { get; set; }

    public TimeSpan CheckinStart { get; set; }

    public TimeSpan? CheckinEnd { get; set; }

    public TimeSpan? CheckoutStart { get; set; }

    public TimeSpan CheckoutEnd { get; set; }

    public int? AddBedFee { get; set; }

    public int? BreakfastPrice { get; set; }

    public int HotelTypeId { get; set; }

    public string HotelFacilities { get; set; }

    public string Email { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<HotelImage> HotelImages { get; set; } = new List<HotelImage>();

    public virtual ICollection<HotelRoom> HotelRooms { get; set; } = new List<HotelRoom>();

    public virtual HotelType HotelType { get; set; }
}