// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class HotelOrderItem
{
    public int Id { get; set; }

    public int HotelRoomId { get; set; }

    public int HotelOrderId { get; set; }

    public virtual HotelOrder HotelOrder { get; set; }

    public virtual HotelRoom HotelRoom { get; set; }
}