// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class HotelImage
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public int HotelId { get; set; }

    public virtual Hotel Hotel { get; set; }
}