// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class MemberActivityRecord
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime ActivityTime { get; set; }

    public bool ActivityType { get; set; }

    public int? SessionDuration { get; set; }

    public string IpAddress { get; set; }

    public byte[] Device { get; set; }

    public virtual Member Member { get; set; }
}