// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class MemberProfile
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Email { get; set; }

    public int? GenderId { get; set; }

    public string ProfileImage { get; set; }

    public string Country { get; set; }

    public virtual Gender Gender { get; set; }

    public virtual Member Member { get; set; }
}