// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class PackageOrderDetail
{
    public int OrderId { get; set; }

    public string Name { get; set; }

    public string IdNumber { get; set; }

    public string Gender { get; set; }

    public DateTime Birthday { get; set; }
}