// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class PackageMemo
{
    public int Id { get; set; }

    public int Days { get; set; }

    public string DaysMemo { get; set; }

    public string Breakfast { get; set; }

    public string Lunch { get; set; }

    public string Dinner { get; set; }

    public int PackageId { get; set; }

    public virtual Package Package { get; set; }
}