// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class PackageOrder
{
    public int Id { get; set; }

    public DateTime OrderDate { get; set; }

    public int PackageId { get; set; }

    public int PackageOrdeStatusId { get; set; }

    public int MemberId { get; set; }

    public int Quantity { get; set; }

    public int TotalAmt { get; set; }

    public virtual Member Member { get; set; }

    public virtual Package Package { get; set; }

    public virtual PackageOrderStatus PackageOrdeStatus { get; set; }
}