// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class Package
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Price { get; set; }

    public int LowestGo { get; set; }

    public DateTime ApplyEndDate { get; set; }

    public DateTime ApplyBeginDate { get; set; }

    public int CanSold { get; set; }

    public int TotalNum { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public string Alert { get; set; }

    public string PriceDescription { get; set; }

    public virtual ICollection<PackageAttractionItem> PackageAttractionItems { get; set; } = new List<PackageAttractionItem>();

    public virtual ICollection<PackageHotelRoomItem> PackageHotelRoomItems { get; set; } = new List<PackageHotelRoomItem>();

    public virtual ICollection<PackageMemo> PackageMemos { get; set; } = new List<PackageMemo>();

    public virtual ICollection<PackageOrder> PackageOrders { get; set; } = new List<PackageOrder>();
}