// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class PackageAttractionItem
{
    public int Id { get; set; }

    public int AttractionId { get; set; }

    public int PackageId { get; set; }

    public virtual Attraction Attraction { get; set; }

    public virtual Package Package { get; set; }
}