// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myapi.Models;

public partial class PointTransction
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string TransactionType { get; set; }

    public string TransactionCategory { get; set; }

    public string Amount { get; set; }

    public DateTime TransactionDate { get; set; }

    public virtual Member Member { get; set; }
}