// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace team1FrontEnd.Server.Models;

public partial class Question
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime DateTime { get; set; }

    public string Question1 { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual Member Member { get; set; }
}